image: gitlab.ar.local:5050/arcloud/docker-images/gitlab-runner:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode --update-snapshots"
  MAVEN_DEPLOYMENT_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/maven"

cache:
  paths:
#  - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS --activate-profiles default compile
  only:
    - develop

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS --activate-profiles default test
  only:
    - develop

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS --activate-profiles default -DaltDeploymentRepository=gitlab-arcloud::default::$MAVEN_DEPLOYMENT_URL deploy
  only:
    - develop

release:
  stage: deploy
  script:
    - mvn versions:set -DgenerateBackupPoms=false -DnewVersion=$CI_COMMIT_TAG
    - mvn $MAVEN_CLI_OPTS --activate-profiles production -DaltDeploymentRepository=gitlab-arcloud::default::$MAVEN_DEPLOYMENT_URL deploy
  rules:
    - if: "$CI_COMMIT_TAG != null"
